workflows:
  ios-simulator-workflow:
    name: iOS Simulator Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      
      - name: Prepare Flutter iOS configuration
        script: |
          flutter precache --ios
          cd ios
          rm -f Flutter/Generated.xcconfig
          cd ..
          flutter build ios --config-only
      
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod cache clean --all
          rm -rf Pods
          rm -rf Podfile.lock
          pod install --repo-update
      
      - name: Build iOS for Simulator
        script: |
          flutter build ios --simulator --debug --no-codesign
    
    artifacts:
      - build/ios/iphonesimulator/**/*.app
    
    publishing:
      email:
        recipients:
          - hamadayoe@gmail.com
        notify:
          success: true
          failure: true
